config/routes.rb
Rails.application.routes.draw do
  namespace :jera_push do
    namespace :admin do

      get '/', to: 'devices#index'

      resources :messages, only: [:index, :show, :new, :create] do
        collection do
          get :device_filter, format: :js
        end
        member do
          get :message_devices_filter, format: :js
        end
      end
      resources :devices, only: [:index]
    end

    namespace :v1 do
      resources :devices, only: [:create] do
        collection do
          delete :destroy
        end
      end
    end
  end
end

app/controllers/jera_push/admin/admin_controller.rb
module JeraPush
  class Admin::AdminController < JeraPush::JeraPushController

    before_filter :authenticate

    def authenticate
      if JeraPush.try(:admin_login)
        authenticate_or_request_with_http_basic do |username, password|
          username == JeraPush.admin_login[:username] && password == JeraPush.admin_login[:password]
        end
      end
    end

  end
end

app/controllers/jera_push/admin/devices_controller.rb
module JeraPush
  class Admin::DevicesController < Admin::AdminController

    def index
      @filter = JeraPush::DeviceFilter.new params_filter
      @devices = @filter.search.order(created_at: :desc).page(params[:page]).per(params[:per])

      respond_to do |format|
        format.js {}
        format.html
      end
    end

    def params_filter
      params.permit(:value, :field, platform: [])
    end

  end
end

app/controllers/jera_push/admin/messages_controller.rb
module JeraPush
  class Admin::MessagesController < Admin::AdminController

    def index
      @messages = JeraPush::MessagePresenter.wrap(JeraPush::Message.all.order(id: :desc))
      @messages = Kaminari.paginate_array(@messages).page(params[:page])
    end

    def show
      @message = JeraPush::Message.find_by id: params[:id]
      @message = JeraPush::MessagePresenter.new @message
      apply_filter
    end

    def new
      @message = JeraPush::Message.new
      apply_filter
    end

    def device_filter
      apply_filter
      respond_to :js
    end

    def message_devices_filter
      apply_filter
      respond_to :js
    end

    def create
      push_message = JeraPush::Service::SendMessage.new(params).call

      if push_message
        flash[:notice] = t('jera_push.admin.messages.new.toast.success')
        redirect_to jera_push_admin_message_path(push_message)
      else
        flash[:error] = t('jera_push.admin.messages.new.toast.error')
        apply_filter
        render :new
      end
    end

    private

      def apply_filter
        @filter = JeraPush::DeviceFilter.new device_filter_params
        @devices = @filter.search.limit(params[:limit]).order(created_at: :desc)
        @message_devices = JeraPush::MessageDevice.includes(:resource, :device).where('message_id = :id and device_id in (:device_ids)', id: params[:id], device_ids: @devices.pluck(:id))
      end

      def device_filter_params
        params.permit(:value, :field, platform: []).merge({ message_id: params[:id] })
      end

  end
end

app/controllers/jera_push/jera_push_controller.rb
module JeraPush
  class JeraPushController < ::ApplicationController
    protect_from_forgery unless: -> { request.format.json? }

    protected

    def render_invalid_params
      render nothing: true, status: :unprocessable_entity
    end

    def render_not_found
      render nothing: true, status: :not_found
    end

    def render_object(object)
      if object.nil? || object.errors.any?
        render_unprocessable_entity(object)
      else
        render_object_success(object)
      end
    end

    private

    def render_object_success(object)
      render json: { data: object, status: :success }, status: :ok
    end

    def render_unprocessable_entity(object)
      render json: {
          data: object,
          errors: object.errors.full_messages,
          status: :unprocessable_entity
        }, status: :ok
    end
  end
end

app/controllers/jera_push/v1/devices_controller.rb
module JeraPush
  class V1::DevicesController < JeraPush::V1::VersionController

    def create
      @device = JeraPush::Device.find_by(token: params[:token], platform: params[:platform])
      if @device.nil?
        @device = JeraPush::Device.create device_params
      else
        @device.update_attributes(resource_id: params[:resource_id])
      end
      render_object(@device)
    end

    def destroy
      @device = JeraPush::Device.find_by(token: params[:token], platform: params[:platform])
      return render_not_found if @device.nil?
      @device.destroy
      render_object(@device)
    end

    private
    def device_params
      params.permit(:token, :platform, :resource_id)
    end
  end
end

app/controllers/jera_push/v1/version_controller.rb
module JeraPush
  class V1::VersionController < JeraPush::JeraPushController

    

  end
end

app/helpers/jera_push/admin/devices_helper.rb
module JeraPush::Admin::DevicesHelper

  def resource_extras(device)
    if JeraPush.resource_attributes && JeraPush.resource_attributes.any?
      return resource_attributes(JeraPush.resource_attributes, device.resource)
    end
    return [device.resource]
  end

  def resource_attributes(attributes, resource)
    if resource
      attrs = attributes.collect do |attribute|
        "#{attribute}: #{resource.send(attribute)}"
      end
      return attrs.delete_if { |v| v.nil?}
    end
  end

  def devices_fields_for_filter_select
    fields = [:token]
    if JeraPush.resource_attributes && JeraPush.resource_attributes.any?
      JeraPush.resource_attributes.each do |attribute|
        fields << attribute
      end
    end
    fields
  end

end

app/helpers/jera_push/admin/messages_helper.rb
module JeraPush::Admin::MessagesHelper

  def format_message(message)
    message
  end

end

app/views/jera_push/admin/devices/_checkbox_list.html.erb
<table class="highlight">
  <thead>
    <tr>
      <th data-field="checkbox"></th>
      <th data-field="id"><%= t('jera_push.admin.devices.attributes.id') %></th>
      <th data-field="token"><%= t('jera_push.admin.devices.attributes.token') %></th>
      <th data-field="platform"><%= t('jera_push.admin.devices.attributes.platform') %></th>
      <th data-field="resource"><%= t('jera_push.admin.devices.attributes.resource') %></th>
      <th>
        <%= button_tag t('jera_push.admin.buttons.send_all'), type: 'button', class: 'btn btn-action', onclick: 'addAllDevices()' %>
      </th>
      <th width="5%">
        <%= button_tag t('jera_push.admin.buttons.remove_all'), type: 'button', class: 'btn btn-action', onclick: 'removeAllDevices()' %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% devices.each do |device| %>
      <tr>
        <td>
          <%= check_box_tag "devices[]", device.id, false, id: "device_#{device.id}" %>
          <%= label_tag "device_#{device.id}", ''%>
        </td>
        <td><%= device.id %></td>
        <td><%= device.token.truncate(40) %></td>
        <td><%= device.platform %></td>
        <td colspan="4">
          <% resource_extras(device).each do |attribute| %>
            <div><%= attribute %></div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jera_push/admin/devices/_filter.html.erb
<div class="filter-container row">
  <%= form_tag filter_path, method: :get, class: 'col s12', remote: true do |f| %>
    <div class="row">
      <% JeraPush::Device.platform.values.each do |platform|  %>
        <div class="input-field col s2">
          <p>
            <%= check_box_tag :"platform[]", platform, filter.platform.include?(platform), id: "platform_#{platform}"  %>
            <label for="platform_<%= platform %>"><%= platform %><label>
          </p>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="input-field col s3">
        <%= select_tag :field, options_for_select(devices_fields_for_filter_select, filter.field) %>
      </div>
      <div class="input-field col s9">
        <div class="col s6">
          <%= text_field_tag :value, filter.value %>
          <label for="value"><%= t('jera_push.admin.filter.value') %></label>
        </div>

        <div class="input-field col s3">
          <%= submit_tag t('jera_push.admin.filter.button'), class: 'btn' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/jera_push/admin/devices/_list.html.erb
<table class="highlight">
  <thead>
    <tr>
      <th data-field="id"><%= t('jera_push.admin.devices.attributes.id') %></th>
      <th data-field="token"><%= t('jera_push.admin.devices.attributes.token') %></th>
      <th data-field="platform"><%= t('jera_push.admin.devices.attributes.platform') %></th>
      <th data-field="resource"><%= t('jera_push.admin.devices.attributes.resource') %></th>
    </tr>
  </thead>
  <tbody>
    <% devices.each do |device| %>
      <tr>
        <td><%= device.id %></td>
        <td><%= device.token.truncate(50) %></td>
        <td><%= device.platform %></td>
        <td>
          <% resource_extras(device).each do |attribute| %>
            <div><%= attribute %></div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jera_push/admin/devices/index.html.erb
<div class="devices-list-container">
  <%= render partial: 'jera_push/admin/devices/filter', locals: {filter_path: jera_push_admin_devices_path, filter: @filter} %>

  <div class="devices-list" id="device_list">
    <%= render partial: 'jera_push/admin/devices/list', locals: {devices: @devices} %>
  </div>

  <div class="center" id="paginator">
    <%= paginate @devices, remote: true %>
  </div>
</div>

app/views/jera_push/admin/devices/index.js.erb
$('#paginator').html('<%= j paginate(@devices, remote: true).to_s %>');

$('#device_list').html("<%= j render partial: 'jera_push/admin/devices/list', locals: {devices: @devices} %>");

app/views/jera_push/admin/messages/_broadcast_message.html.erb
<table class="highlight">
  <thead>
    <tr>
      <th data-field="platform">
        <%= t('jera_push.admin.messages.show.broadcast.platform') %>
      </th>
      <th data-field="status">
        <%= t('jera_push.admin.messages.show.broadcast.status') %>
      </th>
      <th data-field="message">
        <%= t('jera_push.admin.messages.show.broadcast.message') %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @message.broadcast_result.each do |result| %>
      <tr>
        <td><%= result[:platform] %></td>
        <td><%= @message.status %></td>
        <td>
          <% if @message.status.eql?('error') %>
            <%= result[:message] || '-' %>
          <% else %>
            <%= t('jera_push.admin.message_devices.status.success') %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jera_push/admin/messages/_message_attributes.html.erb
<div class="row message-attributes valign-wrapper">
  <div class="input-field col s4">
    <%= text_field_tag 'message[][key]', key %>
    <%= label_tag 'message[][key]', 'Chave' %>
  </div>
  <div class="input-field col s7">
    <%= text_field_tag 'message[][value]' %>
    <%= label_tag 'message[][value]', 'Valor' %>
  </div>
  <div class="col s1">
    <% unless default %>
      <a class="valign btn-floating btn-small waves-effect waves-light" onclick="removeMessageAttribute($(this))">
        <i class="material-icons">remove</i>
      </a>
    <% end %>
  </div>
</div>

app/views/jera_push/admin/messages/_message_device.html.erb
<table class="highlight">
  <thead>
    <tr>
      <th data-field="resource"><%= t('jera_push.admin.message_devices.attributes.resource') %></th>
      <th data-field="status"><%= t('jera_push.admin.message_devices.attributes.status') %></th>
      <th data-field="message"><%= t('jera_push.admin.message_devices.attributes.metadata') %></th>
      <th data-field="info"><%= t('jera_push.admin.message_devices.attributes.device') %></th>
    </tr>
  </thead>
  <tbody>
    <% message_devices.each do |message_device| %>
      <tr>
        <td>
          <% resource_extras(message_device).each do |attribute| %>
            <div><%= attribute %></div>
          <% end %>
        </td>
        <td>
          <%= message_device.status ? t("jera_push.admin.message_devices.status.#{message_device.status}") : t("jera_push.admin.message_devices.status.undefined") %>
        </td>
        <td>
          <% if message_device.status && message_device.status.error? %>
            <div><%= t('jera_push.admin.message_devices.attributes.error_message') %></div>
            <div><%= message_device.error_message %></div>
          <% end %>

          <% if message_device.status && message_device.status.success? %>
            <div><%= t('jera_push.admin.message_devices.attributes.firebase_id') %></div>
            <div><%= message_device.firebase_id %></div>
          <% end %>
        </td>
        <td>
          <div><%= message_device.device.platform %></div>
          <div><%= message_device.device.token.truncate(20) %></div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jera_push/admin/messages/_new.js.erb
$(document).ready(function(){
  $('#device_attributes').hide();

  $('#message_options input[type=radio]').on('change', function(){
    if($(this)[0].value == 'broadcast'){
      $('#device_attributes').hide();
    } else {
      $('#device_attributes').show();
    }
  });
});

function newMessageAttribute(){
  $('#message_attributes_content').append("<%= j render partial: 'jera_push/admin/messages/message_attributes', locals: {key: '', default: false} %>");
};

function removeMessageAttribute(scope){
  scope.parent().parent().remove();
};

function addAllDevices(){
  var devices = $('#device_list_checkbox tr input'), devices_input = '';
  for(var i = 0, l = devices.length; i < l; i++){
    var checkboxValue = devices[i].value;
    devices_input += "<input type='text' name='devices[]' value=" + checkboxValue + " >";
  }
  devices.prop('checked', true);
  $('#message_devices').append(devices_input);
};

function removeAllDevices(){
  $('#message_devices').empty();
  $('#device_list_checkbox tr input').prop('checked', false);
};

app/views/jera_push/admin/messages/device_filter.js.erb
$('#device_list_checkbox').html("<%= j render partial: 'jera_push/admin/devices/checkbox_list', locals: {devices: @devices} %>");

$('#device_list_checkbox tr input').on('change', function(){
  var checkboxValue = $(this)[0].value;
  if($(this).is(':checked')){
    $('#message_devices').append("<input type='text' name='devices[]' value=" + checkboxValue + " >");
  } else {
    $('#message_devices input[value=' + checkboxValue + ']').remove();
  }
});

app/views/jera_push/admin/messages/index.html.erb
<h3><%= t('jera_push.active_record.model.message.other') %></h3>

<table class="bordered">
  <thead>
    <tr>
      <th data-field="id">
        <%= t('jera_push.active_record.messages.attributes.id') %>
      </th>
      <th data-field="content">
        <%= t('jera_push.active_record.messages.attributes.content') %>
      </th>
      <th data-field="date">
        <%= t('jera_push.active_record.messages.attributes.date') %>
      </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td width="5%"><%= message.id %></td>
        <td width="75%"><div class="json-message"><%= message.list_content %></div></td>
        <td width="20%"><%= message.display_created_at %></td>
        <td width="10%"><%= message.show_link %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @messages %>

app/views/jera_push/admin/messages/message_devices_filter.js.erb
$('#device_list').html("<%= j render partial: 'jera_push/admin/messages/message_device', locals: { message_devices: @message_devices} %>");

app/views/jera_push/admin/messages/new.html.erb
<div class="container-messages-new">

  <h3><%= t('jera_push.admin.messages.new.title') %></h3>

  <div class="row">
    <%= form_tag jera_push_admin_messages_path, class: 'col s12' do %>

      <div class="row" id="message_attributes_content">
        <%= render partial: 'jera_push/admin/messages/message_attributes', locals: {key: 'title', default: true} %>
        <%= render partial: 'jera_push/admin/messages/message_attributes', locals: {key: 'body', default: true} %>
      </div>

      <div class="row center">
        <span class="new-attribute" onclick="newMessageAttribute()">
          <%= t('jera_push.admin.messages.new.new_attribute') %>
        </span>
      </div>

      <div class="row options" id="message_options">
        <div class="row">
          <p class="col s3">
            <%= radio_button_tag :type, :broadcast, true, class: 'with-gap' %>
            <%= label_tag :type_broadcast, t('jera_push.admin.messages.new.broadcast') %>
          </p>
          <p class="col s4">
            <%= radio_button_tag :type, :specific, false, class: 'with-gap' %>
            <%= label_tag :type_specific, t('jera_push.admin.messages.new.specific') %>
          </p>
        </div>
      </div>

      <div id="message_devices"></div>

      <%= button_tag type: 'submit', data: { confirm: t('jera_push.admin.messages.new.confirmation') }, class: 'btn btn-submit' do %>
        <%= t('jera_push.admin.buttons.send') %>
        <i class="material-icons right">send</i>
      <% end -%>
    <% end -%>

  </div>

  <div class="device-attributes" id="device_attributes">
    <!-- TODO APLICAR LIMITE NAS CONFIGURAÇÕES DA GEM -->
    <%= render partial: 'jera_push/admin/devices/filter', locals: {filter_path: device_filter_jera_push_admin_messages_path(limit: 50), filter: @filter} %>

    <div class="devices-list checkbox" id="device_list_checkbox"></div>
  </div>

</div>

<script>
  <%= render partial: 'jera_push/admin/messages/new', formats: [:js] %>
</script>

app/views/jera_push/admin/messages/show.html.erb
<div class="messages-show-container">

  <div class="details">
    <h3><%= t('jera_push.active_record.model.message.one') %></h3>

    <span class="field">
      <%= t('jera_push.active_record.messages.attributes.id') %>
    </span>
    <blockquote class="json-message"><%= @message.id %></blockquote>

    <span class="field">
      <%= t('jera_push.active_record.messages.attributes.content') %>
    </span>
    <blockquote class="json-message"><%= @message.display_content %></blockquote>

    <% unless @message.kind.broadcast? %>
      <span class="field">
        <%= t('jera_push.active_record.messages.attributes.status') %>
      </span>
      <blockquote class="json-message">
        <%= @message.status %>
        <%= t('jera_push.admin.messages.failures', value: @message.failure_count) %>
        <%= t('jera_push.admin.messages.success', value: @message.success_count) %>
      </blockquote>
    <% end %>
  </div>

  <% if @message.kind.broadcast? %>
    <h3><%= JeraPush::Message.kind.broadcast.text %></h3>

    <div class="message-info">
      <%= render partial: 'jera_push/admin/messages/broadcast_message', message: @message %>
    </div>
  <% else %>
    <div class="devices">
      <h3><%= t('jera_push.active_record.model.device.other') %></h3>

      <%= render partial: 'jera_push/admin/devices/filter', locals: {filter_path: message_devices_filter_jera_push_admin_message_path(@message), filter: @filter} %>

      <div class="devices-list" id="device_list">
        <%= render partial: 'jera_push/admin/messages/message_device', locals: {message_devices: @message_devices} %>
      </div>
    </div>
  <% end -%>

</div>

app/views/layouts/jera_push/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="<%= jera_push_admin_path %>" class="brand-logo">
      <img src="http://jera.com.br/images/logo-jera-header.png" alt="Jera Software Logo">
    </a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li class="<%= 'active' if current_page?(jera_push_admin_devices_path) %>">
      	<a href="<%= jera_push_admin_devices_path %>">
      		<%= t('jera_push.admin.navbar.devices') %>
    		</a>
    	</li>
      <li class="<%= 'active' if current_page?(jera_push_admin_messages_path) %>">
      	<a href="<%= jera_push_admin_messages_path %>">
      		<%= t('jera_push.admin.navbar.messages') %>
  			</a>
      </li>
      <li class="<%= 'active' if current_page?(new_jera_push_admin_message_path) %>">
        <a href="<%= new_jera_push_admin_message_path %>">
          <%= t('jera_push.admin.navbar.new_message') %>
        </a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/jera_push/jera_push.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JeraPush</title>

  <%= stylesheet_link_tag    'jera_push/jera_push', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jera_push/jera_push', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Let browser know website is optimized for mobile-->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>

	<%= render partial: 'layouts/jera_push/navbar' %>

	<div class="container">
	  <%= yield %>
	</div>

  <% flash.each do |key, value| %>
    <script type="text/javascript">
      Materialize.toast('<%= value %>', 3000, '<%= key %>');
    </script>
  <% end %>

</body>
</html>